version: "3.8"
services:
    app1-server-1:
        build:
            context: ./server/app1
        ports:
            - "5000:5000"
        volumes:
          - ./server/app1:/usr/src/app
        networks:
          - app_network
        environment:
          - SERVER_NAME=app1-server-1

    app1-server-2:
        build:
            context: ./server/app1
        ports:
            - "5001:5000"
        volumes:
          - ./server/app1:/usr/src/app
        networks:
          - app_network
        environment:
          - SERVER_NAME=app1-server-2

    app1-server-backup:
        build:
            context: ./server/app1
        ports:
            - "5002:5000"
        volumes:
          - ./server/app1:/usr/src/app
        networks:
          - app_network
        environment:
          - SERVER_NAME=app1-server-backup

    app2:
        build:
            context: ./server/app2
        ports:
            - "5100:5100"
        volumes:
          - ./server/app2:/usr/src/app
        networks:
          - app_network

    auth:
        build:
            context: ./server/auth
        ports:
            - "5200:5200"
        volumes:
          - ./server/auth:/usr/src/app
        networks:
          - app_network

    nginx:
        restart: always
        build:
            context: ./server/nginx
        ports:
            - "80:80"
        networks:
          - app_network

    ui:
        restart: always
        build:
            context: ./client/ui
        ports:
            - "3000:3000"
        volumes:
          - ./client/ui:/usr/src/app
        networks:
          - app_network

networks:
  app_network:
    driver: bridge
