version: "3.8"
services:
    app1:
        build:
            context: ./node/app1
        ports:
            - "5000:5000"
    app2:
        build:
            context: ./node/app2
        ports:
            - "5100:5100"
    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"